### PR TITLE
Add lark in dolang dependencies

### PR DESCRIPTION
**Pull request by NormannR**

### CODE REVIEW

**Comment by albop** [comment]
Are you sure ? It looks like the project is distributed as lark-parser (https://pypi.org/project/lark-parser/). Granted, there is another package called lark (https://pypi.org/project/lark), which seems more recent. Is it supposed to supersed the older one ? In that case, we don't need lark-parser anymore.

**Comment by NormannR** [comment]
Installing without lark leads to an error. lark-parser seems not enough.

**Comment by albop** [comment]
Then, can you remove lark from pyproject ?

**Comment by albop** [comment]
I meant lark-parser

**Pull request merged**
